USE Jamin;

DROP TABLE IF EXISTS Magazijn;
CREATE TABLE Magazijn (
    Id INT UNSIGNED NOT NULL AUTO_INCREMENT
    ,ProductId INT  UNSIGNED NOT NULL
    ,VerpakkingsEenheidKG DECIMAL(6,2)
    ,AantalAanwezig INT UNSIGNED NULL DEFAULT NULL
    ,IsActief BIT NOT NULL DEFAULT 1
    ,Opmerking VARCHAR(250) NULL DEFAULT NULL
    ,DatumAangemaakt DATETIME(6) NOT NULL DEFAULT NOW(6)
    ,DatumGewijzigd DATETIME(6) NOT NULL DEFAULT NOW(6) ON UPDATE NOW(6)
    
    ,PRIMARY KEY(Id)
    ,CONSTRAINT ProductId FOREIGN KEY (ProductId) REFERENCES Product(Id)
);

DROP TABLE IF EXISTS Product;
CREATE TABLE Product (
    Id INT UNSIGNED NOT NULL AUTO_INCREMENT
    ,Naam VARCHAR(100) NOT NULL
    ,Barcode SMALLINT UNSIGNED NOT NULL
    ,IsActief BIT NOT NULL DEFAULT 1
    ,Opmerking VARCHAR(250) NULL DEFAULT NULL
    ,DatumAangemaakt DATETIME(6) NOT NULL DEFAULT NOW(6)
    ,DatumGewijzigd DATETIME(6) NOT NULL DEFAULT NOW(6) ON UPDATE NOW(6)
    
    ,PRIMARY KEY(Id)
);

DROP TABLE IF EXISTS ProductPerAllergeen;
CREATE TABLE ProductPerAllergeen (
    Id INT UNSIGNED NOT NULL AUTO_INCREMENT
    ,ProductId INT UNSIGNED NOT NULL
    ,AllergeenId INT UNSIGNED NOT NULL
    ,IsActief BIT NOT NULL DEFAULT 1
    ,Opmerking VARCHAR(250) NULL DEFAULT NULL
    ,DatumAangemaakt DATETIME(6) NOT NULL DEFAULT NOW(6)
    ,DatumGewijzigd DATETIME(6) NOT NULL DEFAULT NOW(6) ON UPDATE NOW(6)
    
    ,PRIMARY KEY(Id)
    ,CONSTRAINT ProductId FOREIGN KEY (ProductId) REFERENCES Product(Id)
    ,CONSTRAINT AllergeenId FOREIGN KEY (AllergeenId) REFERENCES Allergeen(Id)
);

DROP TABLE IF EXISTS Allergeen;
CREATE TABLE Allergeen (
    Id INT UNSIGNED NOT NULL AUTO_INCREMENT
    ,Naam VARCHAR(50) NOT NULL
    ,Omschrijving VARCHAR(100) NOT NULL
    ,IsActief BIT NOT NULL DEFAULT 1
    ,Opmerking VARCHAR(250) NULL DEFAULT NULL
    ,DatumAangemaakt DATETIME(6) NOT NULL DEFAULT NOW(6)
    ,DatumGewijzigd DATETIME(6) NOT NULL DEFAULT NOW(6) ON UPDATE NOW(6)
    
    ,PRIMARY KEY(Id)
);

DROP TABLE IF EXISTS ProductPerLeverancier;
CREATE TABLE ProductPerLeverancier (
    Id INT UNSIGNED NOT NULL AUTO_INCREMENT
    ,LeverancierId INT UNSIGNED NOT NULL
    ,ProductId INT UNSIGNED NOT NULL
    ,DatumLevering DATE NOT NULL
    ,Aantal SMALLINT UNSIGNED NOT NULL
    ,DatumEerstVolgendeLevering DATE NULL DEFAULT NULL
    ,IsActief BIT NOT NULL DEFAULT 1
    ,Opmerking VARCHAR(250) NULL DEFAULT NULL
    ,DatumAangemaakt DATETIME(6) NOT NULL DEFAULT NOW(6)
    ,DatumGewijzigd DATETIME(6) NOT NULL DEFAULT NOW(6) ON UPDATE NOW(6)
    
    ,PRIMARY KEY(Id)
);

DROP TABLE IF EXISTS Leverancier;
CREATE TABLE Leverancier (
    Id INT UNSIGNED NOT NULL AUTO_INCREMENT
    ,Naam VARCHAR(100) NOT NULL
    ,ContactPersoon VARCHAR(100) NOT NULL
    ,LeverancierNummer VARCHAR(100) NOT NULL
    ,Mobiel VARCHAR(100) NOT NULL
    ,IsActief BIT NOT NULL DEFAULT 1
    ,Opmerking VARCHAR(250) NULL DEFAULT NULL
    ,DatumAangemaakt DATETIME(6) NOT NULL DEFAULT NOW(6)
    ,DatumGewijzigd DATETIME(6) NOT NULL DEFAULT NOW(6) ON UPDATE NOW(6)
    
    ,PRIMARY KEY(Id)
);